services: # To run locally do docker compose -f docker-compose.yml -f docker-compose.local.yml up --build
  backend:
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "5173:5173"
    depends_on:
      - backend